version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
        - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  task-organizer:

